/**
 * Admin accounts.
 *
 * Ported from the Supabase `admin_users` table. The difference: the id is now a
 * Mongo ObjectId generated by the server rather than a foreign key into
 * `auth.users`. Supabase Auth is gone, so nothing external to reference.
 *
 * `passwordHash` is a bcrypt hash — plaintext passwords are never stored, never
 * logged and never sent to the browser.
 */

import { Schema, model, type InferSchemaType } from 'mongoose';

const adminSchema = new Schema(
  {
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      index: true,
    },
    passwordHash: { type: String, required: true },
    fullName: { type: String, default: null, trim: true, maxlength: 120 },
    role: {
      type: String,
      enum: ['owner', 'agent'],
      default: 'agent',
      required: true,
    },
    active: { type: Boolean, default: true },
    lastLoginAt: { type: Date, default: null },
  },
  {
    timestamps: true,
    // `passwordHash` must never leave the server. Every controller serialises
    // admins through toAdminDTO(), but this is the backstop.
    toJSON: {
      transform(_doc, ret: Record<string, unknown>) {
        delete ret.passwordHash;
        delete ret.__v;
        return ret;
      },
    },
  },
);

export type AdminDoc = InferSchemaType<typeof adminSchema>;
export const Admin = model('Admin', adminSchema);
